batch_size: 16
epochs: 120
ip_img_rows: 512
ip_img_cols: 512
nw_img_rows: 448
nw_img_cols: 448
classes: 30
pth_data: /home/ddot/document/clef16/data
pth_utils: /home/ddot/document/clef16/utils
pth_models: /home/ddot/document/clef16/models
pth_weights: /home/ddot/document/clef16/weights
pth_hist: /home/ddot/document/clef16/history
