batch_size: 16
epochs: 120
ip_img_rows: 256
ip_img_cols: 256
nw_img_rows: 224
nw_img_cols: 224
classes: 30
pth_data: /home/jakep/document/clef16/data
pth_utils: /home/jakep/document/clef16/utils
pth_models: /home/jakep/document/clef16/models
pth_weights: /media/jakep/Elements/document_weights/
pth_hist: /home/jakep/document/clef16/history
